version: "3"
services:
  app:
    image: node:12-alpine
    command: sh -c "npm install --production && npm start"
    ports:
      - $PORT:$PORT
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
    env_file: .env

  postgres:
    image: postgres:12
    volumes:
      - miniforum-postgres-data:/var/lib/postgresql/data
      - ./postgresql/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      # For testing purposes
      - $LOCALHOST_DB_BINDPORT:5432

volumes:
  miniforum-postgres-data:
