apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniforum-persistent-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/miniforum
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: miniforum-persistent-volume-claim
spec:
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi