apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: miniforum-statefulset
spec:
  serviceName: "miniforum-postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: postgres
        image: postgres:12
        envFrom:
        - configMapRef:
            name: miniforum-configmap
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: miniforum-persistent-volume-claim
